version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    restart: always
    ports: 
      - 51773
      - ${IRIS_PORT}:52773
      - 53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
      - ./src/csp:/usr/irissys/mgr/csp/irisapp