version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    restart: always
    ports: 
      - 1972
      - 52773:52773/tcp
      - 53773
    volumes:
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
      - ./src/csp:/usr/irissys/mgr/csp/irisapp
